### ISSUE TITLE
Not able to view recent answers, unanswered, updates tab by clicking on them

### ISSUE THREAD

**Issue by shiprakush** [OfficeDev/microsoft-teams-crowdsourcer-app#11]
When I click on Recent Answers tab, unanswered tab , recent updates tab, Crowdsourcer does not show any answers!! Please suggest.

**Comment by rashmi-dixit** [comment]
It takes some time to reflect in ME (messaging extensions). Were you able to see data after 15-20 mins?
For ME, the data shown is pulled from blob storage which is updated by azure function. This function runs at defined interval to update latest data from knowledge base into blob storage. For details refer https://github.com/OfficeDev/microsoft-teams-crowdsourcer-app/wiki/Solution-Overview

**Comment by shiprakush** [comment]
@rashmi-dixit  No, I am not to see data even after 1 hr. I don't know what's the issue. Please suggest.

**Comment by shiprakush** [comment]
@rashmi-dixit  Just to clarify, I am talking about the scenario when I try to search from the search box:-Please see the screenshots attached.
![Screenshot Error](https://user-images.githubusercontent.com/56202035/83990024-e7fce100-a90d-11ea-97a2-ab3205a3bad3.PNG)
![Screenshot Error 2](https://user-images.githubusercontent.com/56202035/83990026-e8957780-a90d-11ea-998a-ef3c92198f9c.PNG)

**Comment by rashmi-dixit** [comment]
@shiprakush - It works only through ME (Messaging extensions)
![image](https://user-images.githubusercontent.com/57787129/84465440-a022e480-ac94-11ea-987e-d666a9d64fd8.png)
