### ISSUE TITLE
Validate Deployment Failed

### ISSUE THREAD

**Issue by vslum78** [OfficeDev/microsoft-teams-crowdsourcer-app#9]
Hi,

I followed the Deployment Guide and encountered an error in Step 2: Deploy to your Azure subscription.  I clicked on the "Deploy to Azure" button, which brought me to the "Custom deployment" page in Azure.  I selected a subscription and my resource group, entered the base resource name and specified the 3 values I obtained from Step 1 to "Bot Client Id", "Bot Client Secret" and "Tenant Id".  I clicked on "Purchase" and got the following error

`
The template deployment 'Microsoft.Template' is not valid according to the validation procedure. The tracking id is 'c151cd6a-a060-4d8e-938d-4e91108670e3'. See inner errors for details.`

Thank You

**Comment by rashmi-dixit** [comment]
Please confirm if the resource group location is other than west us?

**Comment by vslum78** [comment]
You are correct, the resource group location is not west us, it's southeast asia.  Is that an issue?

**Comment by rashmi-dixit** [comment]
Please try the deployment again. A change has been pushed to fix this issue.
